version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '9100:9100'
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
