version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '9100:9100'
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
