# Dockerfile.nginx
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY ./.nginx/html/dist /home

COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf

COPY ./.nginx/cert/* /etc/letsencrypt/live/doorsapp.ru/



ENTRYPOINT ["nginx", "-g", "daemon off;"]